name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&'
template: |
  <!-- Write your release notes here -->


  ## Merged PRs
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG_NAME
