name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-overview.yml
  workflow_dispatch: 
 
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    
    - name: Docker Hub Description  
      uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: ${{ secrets.DOCKER_HUB_USERNAME }}/periodt
        short-description: "${{ github.event.repository.description }} | github.com/andreuinyu/periodt"
        enable-url-completion: true