name: JS & Python Lint w/ CodeQL & Eslint
on:
  schedule:
    - cron: '0 7 * * 5' # Friday 7am UTC
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  codeql-python:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
 
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python
          queries: security-and-quality
          source-root: ./backend
 
      - name: Perform analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:python"
 
  codeql-javascript:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
 
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript
          queries: security-and-quality
          source-root: ./frontend
 
      - name: Perform analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:javascript"
    
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
 
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
 
      - name: Install ESLint
        run: npm install -g eslint
 
      - name: Run ESLint
        run: eslint ./frontend/